name: create pages
on: [push]
jobs:
  create_pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: "main"

      - name: Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.84.4'

      - name: build pages
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3        
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
