name: cmd test
on: [push]
jobs:
  cmd-test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          mkdir ~/.ssh
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
          echo ${{ secrets.WEBLOG_DEPLOY_SECRET }} > ~/.ssh/id_rsa
          chmod 0400 ~/.ssh/id_rsa
      - run: bash scripts/deploy-pages.bash
