name: cmd test
on: [push]
jobs:
  cmd-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello Github Actions" > index.html
      - run: |
          git config --local user.name "${GITHUB_USER}"
          git config --local user.email ${GITHUB_EMAIL}
          git remote set-url origin git@github.com:${GITHUB_REPOSITORY}.git
          git add docs
          git commit -m "Actions Test."
          git push origin main

