name: cmd test
on: [push]
jobs:
  cmd-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello Github Actions" > index.html
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.7.3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
